const questoesNatureza = [
{ id:1, subject:"Natureza", text:"Fotossíntese ocorre em:", options:{A:"Mitocôndria",B:"Cloroplasto",C:"Núcleo",D:"Ribossomo",E:"Lisossomo"}, correct:"B"},
{ id:2, subject:"Natureza", text:"A respiração celular produz:", options:{A:"Oxigênio",B:"Glicose",C:"ATP",D:"Água apenas",E:"Nitrogênio"}, correct:"C"},
{ id:3, subject:"Natureza", text:"Energia cinética depende de:", options:{A:"Tempo",B:"Massa e velocidade",C:"Temperatura",D:"Pressão",E:"Volume"}, correct:"B"},
{ id:4, subject:"Natureza", text:"pH ácido é:", options:{A:">7",B:"=7",C:"<7",D:"=14",E:"Neutro"}, correct:"C"},
{ id:5, subject:"Natureza", text:"DNA armazena:", options:{A:"Energia",B:"Informação genética",C:"Proteínas",D:"Lipídios",E:"Água"}, correct:"B"},
{ id:6, subject:"Natureza", text:"A 1ª lei de Newton trata da:", options:{A:"Ação e reação",B:"Inércia",C:"Força resultante",D:"Gravidade",E:"Energia"}, correct:"B"},
{ id:7, subject:"Natureza", text:"A água é considerada solvente universal por:", options:{A:"Ser pesada",B:"Polaridade",C:"Cor",D:"Temperatura",E:"Pressão"}, correct:"B"},
{ id:8, subject:"Natureza", text:"Mitose resulta em:", options:{A:"2 células iguais",B:"4 diferentes",C:"1 célula",D:"Gametas",E:"Mutação"}, correct:"A"},
{ id:9, subject:"Natureza", text:"Meiose produz:", options:{A:"Células iguais",B:"Gametas",C:"Tecidos",D:"Órgãos",E:"ATP"}, correct:"B"},
{ id:10, subject:"Natureza", text:"Velocidade média é:", options:{A:"Tempo/distância",B:"Distância/tempo",C:"Massa/tempo",D:"Força/massa",E:"Energia/tempo"}, correct:"B"},
{ id:11, subject:"Natureza", text:"A força peso depende de:", options:{A:"Volume",B:"Massa e gravidade",C:"Tempo",D:"Temperatura",E:"Pressão"}, correct:"B"},
{ id:12, subject:"Natureza", text:"Estado gasoso tem:", options:{A:"Forma fixa",B:"Volume fixo",C:"Forma e volume variáveis",D:"Rigidez",E:"Alta densidade"}, correct:"C"},
{ id:13, subject:"Natureza", text:"Reação endotérmica:", options:{A:"Libera calor",B:"Absorve calor",C:"Não troca energia",D:"Congela",E:"Evapora"}, correct:"B"},
{ id:14, subject:"Natureza", text:"Reação exotérmica:", options:{A:"Absorve calor",B:"Libera calor",C:"Não reage",D:"Solidifica",E:"Condensa"}, correct:"B"},
{ id:15, subject:"Natureza", text:"Proteínas são formadas por:", options:{A:"Açúcares",B:"Aminoácidos",C:"Ácidos graxos",D:"Nucleotídeos",E:"Sais"}, correct:"B"},
{ id:16, subject:"Natureza", text:"Lipídios têm função:", options:{A:"Informação genética",B:"Reserva energética",C:"Transporte de oxigênio",D:"Defesa",E:"Movimento"}, correct:"B"},
{ id:17, subject:"Natureza", text:"O coração faz parte do sistema:", options:{A:"Digestório",B:"Circulatório",C:"Respiratório",D:"Nervoso",E:"Excretor"}, correct:"B"},
{ id:18, subject:"Natureza", text:"O pulmão realiza:", options:{A:"Digestão",B:"Trocas gasosas",C:"Circulação",D:"Filtração",E:"Contração"}, correct:"B"},
{ id:19, subject:"Natureza", text:"Ecossistema envolve:", options:{A:"Apenas seres vivos",B:"Seres vivos e ambiente",C:"Apenas água",D:"Apenas solo",E:"Apenas clima"}, correct:"B"},
{ id:20, subject:"Natureza", text:"Cadeia alimentar representa:", options:{A:"Energia",B:"Fluxo de energia",C:"Água",D:"Clima",E:"Solo"}, correct:"B"},
{ id:21, subject:"Natureza", text:"Força é:", options:{A:"Energia",B:"Interação que altera movimento",C:"Velocidade",D:"Tempo",E:"Temperatura"}, correct:"B"},
{ id:22, subject:"Natureza", text:"Aceleração é:", options:{A:"Velocidade constante",B:"Variação da velocidade",C:"Distância",D:"Tempo",E:"Massa"}, correct:"B"},
{ id:23, subject:"Natureza", text:"Átomo é composto por:", options:{A:"Moléculas",B:"Prótons, nêutrons e elétrons",C:"Células",D:"Água",E:"Energia"}, correct:"B"},
{ id:24, subject:"Natureza", text:"Elemento químico é definido por:", options:{A:"Massa",B:"Número de prótons",C:"Volume",D:"Energia",E:"Cor"}, correct:"B"},
{ id:25, subject:"Natureza", text:"Mistura homogênea apresenta:", options:{A:"Fases visíveis",B:"Uma fase",C:"Duas fases",D:"Sólido",E:"Gás"}, correct:"B"},
{ id:26, subject:"Natureza", text:"Mistura heterogênea apresenta:", options:{A:"Uma fase",B:"Mais de uma fase",C:"Gás",D:"Líquido",E:"Energia"}, correct:"B"},
{ id:27, subject:"Natureza", text:"Calor é:", options:{A:"Temperatura",B:"Energia em trânsito",C:"Massa",D:"Volume",E:"Pressão"}, correct:"B"},
{ id:28, subject:"Natureza", text:"Temperatura mede:", options:{A:"Energia total",B:"Agitação das partículas",C:"Volume",D:"Pressão",E:"Força"}, correct:"B"},
{ id:29, subject:"Natureza", text:"Trabalho na física é:", options:{A:"Tempo",B:"Força x deslocamento",C:"Energia parada",D:"Massa",E:"Velocidade"}, correct:"B"},
{ id:30, subject:"Natureza", text:"Energia potencial depende de:", options:{A:"Velocidade",B:"Posição",C:"Tempo",D:"Temperatura",E:"Pressão"}, correct:"B"}
];